plugins {
    id "java"
}

configure([tasks.compileJava]) {
    sourceCompatibility = 16
    options.release = 8

    javaCompiler = javaToolchains.compilerFor {
        languageVersion = JavaLanguageVersion.of(21)
    }
}

compileTestJava {
    sourceCompatibility = targetCompatibility = 8
}

test {
    javaLauncher = javaToolchains.launcherFor {
        languageVersion = JavaLanguageVersion.of(8)
    }

    def pluginProject = project(":jabel-javac-plugin")
    dependsOn(":jabel-javac-plugin:jar")

    def pluginJarProvider = pluginProject.layout.buildDirectory.file("libs/jabel-javac-plugin.jar")
    def jdk21JavacProvider = javaToolchains.compilerFor {
        languageVersion = JavaLanguageVersion.of(21)
    }.map { it.executablePath.asFile }

    // Used by RecordBytecodeTest to compile a record in a fresh javac process.
    doFirst {
        File pluginJar = pluginJarProvider.get().asFile
        FileCollection pluginDeps = pluginProject.configurations.getByName("runtimeClasspath")
        String pluginClasspath = files(pluginJar, pluginDeps).asPath

        systemProperty "jabel.test.pluginClasspath", pluginClasspath
        systemProperty "jabel.test.javac", jdk21JavacProvider.get().path
    }

    inputs.file(pluginJarProvider).withPropertyName("jabelPluginJar")
    inputs.files(jdk21JavacProvider).withPropertyName("jabelJavac")
}

dependencies {
    annotationProcessor project(":jabel-javac-plugin")
    compileOnly project(":jabel-javac-plugin")

    testImplementation 'junit:junit:4.13.2'
    testImplementation 'net.bytebuddy:byte-buddy:1.14.9'
}
